# Generated by Django 3.2.8 on 2021-11-02 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='last_name',
            new_name='capacity',
        ),
    ]
