# Generated by Django 3.2.8 on 2021-11-02 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_rename_last_name_room_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolled',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_course', to='university.course'),
        ),
    ]
